const Sequelize = require('sequelize')
const sequelize = require('../database/database')

const Model = Sequelize.Model

class Task extends Model{}
Task.init({
	customer_id:{
		type:Sequelize.INTEGER(11),
		allowNull:false
	},
	personnel_id:{
		type:Sequelize.INTEGER(11),
		allowNull:false
	},
	task_status_id:{
		type:Sequelize.INTEGER(11),
		allowNull:false
	},
	created_by:{
		type:Sequelize.INTEGER(11),
		allowNull:false
	},
	created:{
		type:Sequelize.DATE,
		allowNull:false
	},
	modified_by:{
		type:Sequelize.INTEGER(11),
		allowNull:false
	},
	last_modified:{
		type:Sequelize.DATE,
		allowNull:false
	},
	in_progress:{
		type:Sequelize.DATE,
		allowNull:true
	},
	completed:{
		type:Sequelize.DATE,
		allowNull:true
	},
	deferred:{
		type:Sequelize.DATE,
		allowNull:true
	},
	customer_first_name:{
		type:Sequelize.STRING(100),
		allowNull:true
	},
	customer_last_name:{
		type:Sequelize.STRING(100),
		allowNull:true
	},
	customer_city:{
		type:Sequelize.STRING(100),
		allowNull:true
	},
	customer_username:{
		type:Sequelize.STRING(100),
		allowNull:true
	},
	inserted:{
		type:Sequelize.DATE,
		allowNull:true
	},
	personnel_first_name:{
		type:Sequelize.STRING(100),
		allowNull:true
	},
	personnel_other_name:{
		type:Sequelize.STRING(100),
		allowNull:true
	},
	personnel_phone:{
		type:Sequelize.STRING(50),
		allowNull:true
	},
	task_status_name:{
		type:Sequelize.STRING(50),
		allowNull:true
	},
	customer_location:{
		type:Sequelize.STRING(200),
		allowNull:true
	},
	customer_gender:{
		type:Sequelize.STRING(10),
		allowNull:true
	},
	customer_age:{
		type:Sequelize.INTEGER(11),
		allowNull:true
	},
	customer_access_code:{
		type:Sequelize.INTEGER(1),
		allowNull:true
	},
	customer_splash_page:{
		type:Sequelize.INTEGER(1),
		allowNull:true
	},
	customer_mpesa:{
		type:Sequelize.INTEGER(1),
		allowNull:true
	},
	customer_autoplay:{
		type:Sequelize.INTEGER(1),
		allowNull:true
	},
	customer_comments:{
		type:Sequelize.TEXT,
		allowNull:true
	},
	customer_updated:{
		type:Sequelize.DATE,
		allowNull:true
	},
	customer_updated_by:{
		type:Sequelize.INTEGER(11),
		allowNull:true
	},
	agentId:{
		type:Sequelize.INTEGER(11),
		allowNull:true
	},
	customerId:{
		type:Sequelize.INTEGER(11),
		allowNull:true
	},

},{sequelize,modelName:'task',timestamps:false})

module.exports = Task